site_name: Documentation Reach RTK en Français
theme_dir: docstheme/material
site_favicon: favicon.ico
repo_url: https://github.com/ecolowtech/reach-docs
extra:
  palette:
    primary: light blue
    accent: light blue
  logo: img/logo.png
  social:
    - type: github
      link: https://github.com/emlid
    - type: twitter
      link: https://twitter.com/emlidtech
    - type: facebook
      link: https://facebook.com/emlidtech
  google_analytics:
    - UA-100967086-1
    - auto

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)

pages:
- Introduction: index.md
- Alimentation: power-supply.md
- Positionner l'antenne: antenna-placement.md
- Intégration matérielle: hardware-integration.md
- ReachView:
  - Introduction: common/reachview/index.md
  - Paramètres: common/reachview/settings.md
  - Statut: common/reachview/status.md
  - Relevés: common/reachview/survey.md
  - Paramètres RTK: common/reachview/rtk-settings.md
  - Corrections en entrée: common/reachview/correction-input.md
  - Export de la Position: common/reachview/position-output.md
  - Mode Station Fixe: common/reachview/base-mode.md
  - Journalisation: common/reachview/logging.md
  - Contrôler une caméra: common/reachview/camera-control.md
  - Wi-Fi/Bluetooth: common/reachview/connectivity.md
  - Reprogrammer le Firmware: common/reachview/firmware-reflashing.md
  - Changelogs: common/reachview/changelogs.md
- Signaux LED: led-status.md
- Specifications: specs.md
- Démarrage rapide: quickstart.md
- Tutoriels:
  - Comment fonctionne le RTK: common/tutorials/rtk-introduction.md
  - Intégration ArduPilot: ardupilot-integration.md
  - Post-traitement GPS: common/tutorials/gps-post-processing.md
  - Sortie Bluetooth et Positions Fictives Android: common/tutorials/mock-location.md
